---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    nexus:
      cli:
        ssl:
          verify: false

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[nexus::default]
    attributes: